package httpapi

import (
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"time"
	"unicode"

	"github.com/nahrx/eform/internal/models"
)

/* Offline queue reporting.

   Devices in offline mode hold answers and photos that exist nowhere else. Until a
   device reports in, a backlog stranded on someone's phone is invisible to the
   office — and if that phone breaks, the work is simply gone with no trace that it
   ever existed.

   The endpoint requires a valid respondent session. That is the safe choice, and it
   has a consequence worth stating plainly: the most common failure is an expired
   respondent token, and a device in that state cannot report either. So the device
   reports its state continuously while it still can, and the dashboard treats the
   AGE of the newest report as a signal in its own right. A report that says "2
   pending" and then goes quiet for a week is exactly the case to chase. */

const (
	maxQueueReportBody  = 64 << 10 // a report is counts and short strings, nothing more
	maxQueueReportItems = 50
	maxQueueErrorLen    = 200
	maxDeviceIDLen      = 64
	maxUserAgentLen     = 200
)

type queueReportItemIn struct {
	Kind     string     `json:"kind"`
	Status   int        `json:"status"`
	Error    string     `json:"error"`
	QueuedAt *time.Time `json:"queuedAt"`
	FailedAt *time.Time `json:"failedAt"`
	Attempts int        `json:"attempts"`
}

type queueReportIn struct {
	DeviceID       string              `json:"deviceId"`
	Pending        int                 `json:"pending"`
	Failed         int                 `json:"failed"`
	Files          int                 `json:"files"`
	OldestQueuedAt *time.Time          `json:"oldestQueuedAt"`
	Items          []queueReportItemIn `json:"items"`
}

// Device ids are generated by the page, but they arrive over the wire and end up in
// an admin's browser, so only an opaque token shape is accepted.
func cleanDeviceID(s string) string {
	s = strings.TrimSpace(s)
	if len(s) > maxDeviceIDLen {
		s = s[:maxDeviceIDLen]
	}
	var b strings.Builder
	for _, r := range s {
		if r == '-' || r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// Error texts come from whatever the server said, but a hostile client can send
// anything, so length is capped and control characters are dropped.
func cleanErrorText(s string) string {
	s = strings.Map(func(r rune) rune {
		if r == '\n' || r == '\t' {
			return ' '
		}
		if unicode.IsControl(r) {
			return -1
		}
		return r
	}, s)
	s = strings.TrimSpace(s)
	if len(s) > maxQueueErrorLen {
		s = s[:maxQueueErrorLen]
	}
	return s
}

func clampCount(n int) int {
	if n < 0 {
		return 0
	}
	if n > 100000 {
		return 100000
	}
	return n
}

// queueReport records what one device is still holding for this form.
func (s *Server) queueReport(w http.ResponseWriter, r *http.Request) {
	sh, ok := s.resolveShare(w, r)
	if !ok {
		return
	}
	rc := respondentFrom(r.Context())

	var in queueReportIn
	dec := json.NewDecoder(io.LimitReader(r.Body, maxQueueReportBody))
	if err := dec.Decode(&in); err != nil {
		writeErr(w, http.StatusBadRequest, "invalid format")
		return
	}
	device := cleanDeviceID(in.DeviceID)
	if device == "" {
		writeErr(w, http.StatusBadRequest, "device id is required")
		return
	}

	// Re-marshal from a validated struct instead of passing the client's JSON
	// through: this ends up rendered in an admin's browser, and storing raw
	// caller-supplied structure is how that becomes someone else's problem later.
	items := make([]queueReportItemIn, 0, maxQueueReportItems)
	for _, it := range in.Items {
		if len(items) >= maxQueueReportItems {
			break
		}
		kind := it.Kind
		if kind != "file" {
			kind = "response"
		}
		status := it.Status
		if status < 0 || status > 599 {
			status = 0
		}
		items = append(items, queueReportItemIn{
			Kind:     kind,
			Status:   status,
			Error:    cleanErrorText(it.Error),
			QueuedAt: it.QueuedAt,
			FailedAt: it.FailedAt,
			Attempts: clampCount(it.Attempts),
		})
	}
	raw, err := json.Marshal(items)
	if err != nil {
		writeErr(w, http.StatusBadRequest, "invalid format")
		return
	}

	ua := r.UserAgent()
	if len(ua) > maxUserAgentLen {
		ua = ua[:maxUserAgentLen]
	}

	rep := &models.OfflineQueueReport{
		FormID:         sh.FormID,
		RespondentID:   rc.RespondentID,
		DeviceID:       device,
		Pending:        clampCount(in.Pending),
		Failed:         clampCount(in.Failed),
		Files:          clampCount(in.Files),
		OldestQueuedAt: in.OldestQueuedAt,
		Items:          raw,
		UserAgent:      ua,
	}
	if err := s.st.UpsertOfflineQueueReport(r.Context(), rep); err != nil {
		writeErr(w, http.StatusInternalServerError, "server error")
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// listQueueReports shows an admin which devices are still holding data for a form.
func (s *Server) listQueueReports(w http.ResponseWriter, r *http.Request) {
	f, ok := s.ensureFormAccess(w, r, r.PathValue("id"))
	if !ok {
		return
	}
	reps, err := s.st.ListOfflineQueueReports(r.Context(), f.ID)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, "failed to fetch data")
		return
	}
	pending, failed := 0, 0
	for _, rep := range reps {
		pending += rep.Pending
		failed += rep.Failed
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"reports": reps,
		"devices": len(reps),
		"pending": pending,
		"failed":  failed,
	})
}
